# Generated by Django 3.2.25 on 2024-06-29 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(unique=True)),
                ('table_size', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')], default=2)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
            options={
                'ordering': ['table_id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('reservation_date', models.CharField(max_length=10)),
                ('reservation_time', models.IntegerField(choices=[(1, '10:00'), (2, '10:30'), (3, '11:00'), (4, '11:30'), (5, '12:00'), (6, '12:30'), (7, '13:00'), (8, '13:30'), (9, '14:00'), (10, '18:00'), (11, '18:30'), (12, '19:00'), (13, '19:30'), (14, '20:00'), (15, '20:30')], default=1)),
                ('number_guests', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('special_requests', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('booked_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_table', to='bookings.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reservation_date', 'reservation_time', 'booked_table'],
            },
        ),
    ]
